"""
HAZ UN PROGRAMA QUE PERMITA GENERAR UN MENU DE GESTION DE ENTRADA PARA UN CONCIERTO DE HIP HOP, CON MOVIMIENTO ORIGINAL CON DIFERENTES SHOW
EL MENU DEBE PERMITIR MOSTRAR 4 OPCIONES:
1° COMPRAR ENTRADAS
2° CAMBIAR DE SHOW
3° MOSTRAR STOCK DE FUNCIONES
4° SALIR
TODAS LAS OPCIONES DEL MENU DEBEN IMPLEMENTAR FUNCIONES SEPARADAS DEL CODIGO PRINCIPAL(MAINE)
OPCION NUMERO 1
COMPRAR ENTRADA
INGRESAR NOMBRE
RUT
DIRECCION 
SELECCIONAR EL SHOW
TODO POR SEPARADO.
PARA QUE LA COMPRA SEA EXITOZSA

OPCION 2
NOMBRE DEL COMPRDOR NO REPETIRSE
LA SELECCION DEL SHOW DEBE PERMITIR UNO DE LOS DOS SHOW

SHOWS:
MOVIMIENTO ORIGINAL CON LOS TRIPULANTES
MOVIMIENTO ORIGINAL CON SONRISA

EN LA FUNCION NUMERO UNO TIENE QUE HABER 50 PUESTOS DISPONIBLES
Y EN LA SEGUNDA 60 PUESTOS

EN CASO DE CUMPLIR TODAS LAS FUNCIONES OSTRAR MENSAJE DE COMPRA EXITOSZA

OPCION NUMERO 2

DEBE TENER LA POSIBILIDAD DE CAMBIAR DE SHOW

OPCION NUMERO 3

DEBE PERMITIR MOSTRAR LA DISPONIBILIDAD DE SILLAS

OPCION NUMERO 4

SALIR

ULTIMA PETICION SI EL USUARIO INGRESA UNA OPCION NO PERMITIDA SOLICITARLE NUEVAMENTE LAS OPCIONES PERMITIDAS
"""